#!/sbin/openrc-run
# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="${RC_SVCNAME} daemon"
description="Proxies NDP messages between interfaces."
command="/usr/bin/ndppd-1"
pidfile="/var/run/ndppd-1.pid"
configfile="/etc/ndppd-1.conf"
command_args="-p $pidfile -c ${configfile}"
supervisor=supervise-daemon
supervise_daemon_args="--respawn-period 15 --respawn-delay 3 --respawn-max 4"

depend() {
	use net
}
