#!/sbin/openrc-run
# Copyright 1999-2020 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

name="bitwarden_rs daemon"
description="Unofficial Bitwarden compatible server written in Rust"
command="/usr/bin/bitwarden_rs"
command_user="bitwarden:bitwarden"
pidfile="/run/${RC_SVCNAME}.pid"
supervisor=supervise-daemon
supervise_daemon_args="--pidfile ${pidfile}"

start_pre() {
	set -o allexport
	source "${BITWARDEN_RS_CONFIG}"
	set +o allexport
}
